# Generated by Django 2.0.5 on 2020-08-01 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20170511_0701'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('no', 'show')},
        ),
    ]
