# Generated by Django 2.0.5 on 2020-08-01 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_live', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookedseat',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='bookedseat',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='bookedseat',
            name='seat',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='paid_by',
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='seat',
            name='show',
        ),
        migrations.RemoveField(
            model_name='theatre',
            name='admin_id',
        ),
        migrations.RemoveField(
            model_name='show',
            name='theatre',
        ),
        migrations.DeleteModel(
            name='BookedSeat',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
        migrations.DeleteModel(
            name='Theatre',
        ),
    ]
